<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="SpaceOS.Modules.Hosting" Version="0.1.0-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceOS.Modules.Scheduling.Domain\SpaceOS.Modules.Scheduling.Domain.csproj" />
  </ItemGroup>

</Project>
