// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Scheduling.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260728152938_InitialSchedulingSchema")]
    partial class InitialSchedulingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Audit.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("dispatched_at_utc IS NULL");

                    b.ToTable("outbox_messages", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Audit.SchedulingAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_tenant_time");

                    b.ToTable("audit_entries", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Resources.CapacityReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resource_key");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("State", "ExpiresAtUtc")
                        .HasDatabaseName("ix_reservations_state_expiry");

                    b.HasIndex("ResourceKey", "StartUtc", "EndUtc")
                        .HasDatabaseName("ix_reservations_resource_interval");

                    b.ToTable("capacity_reservations", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Resources.ResourceCalendarRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("capacity");

                    b.Property<string>("CapacityPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capacity_policy");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("resource_key");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ResourceKey", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ux_calendar_resource_revision");

                    b.ToTable("resource_calendar_revisions", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid")
                        .HasColumnName("project_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schedule_runs_tenant_id");

                    b.ToTable("schedule_runs", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Standards.OperationStandard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SourceTaskKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_task_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("_qualifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("qualifiers");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SourceTaskKey")
                        .HasDatabaseName("ix_standards_tenant_source_key");

                    b.ToTable("operation_standards", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Resources.CapacityReservation", b =>
                {
                    b.OwnsOne("SpaceOS.Modules.Scheduling.Domain.Schedules.KernelWorkScope", "Scope", b1 =>
                        {
                            b1.Property<Guid>("CapacityReservationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Epic")
                                .HasColumnType("uuid")
                                .HasColumnName("epic_ref");

                            b1.Property<Guid>("Project")
                                .HasColumnType("uuid")
                                .HasColumnName("project_ref");

                            b1.Property<Guid>("Task")
                                .HasColumnType("uuid")
                                .HasColumnName("task_ref");

                            b1.HasKey("CapacityReservationId");

                            b1.ToTable("capacity_reservations", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("CapacityReservationId");
                        });

                    b.Navigation("Scope")
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Resources.ResourceCalendarRevision", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Resources.RecurringShift", "Shifts", b1 =>
                        {
                            b1.Property<Guid>("ResourceCalendarRevisionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("IsoWeekday")
                                .HasColumnType("integer");

                            b1.HasKey("ResourceCalendarRevisionId", "Id");

                            b1.ToTable("resource_calendar_revisions", "scheduling");

                            b1.ToJson("shifts");

                            b1.WithOwner()
                                .HasForeignKey("ResourceCalendarRevisionId");

                            b1.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Resources.DayRange", "Breaks", b2 =>
                                {
                                    b2.Property<Guid>("RecurringShiftResourceCalendarRevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("RecurringShiftId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("EndMinuteOfDay")
                                        .HasColumnType("integer");

                                    b2.Property<int>("StartMinuteOfDay")
                                        .HasColumnType("integer");

                                    b2.HasKey("RecurringShiftResourceCalendarRevisionId", "RecurringShiftId", "Id");

                                    b2.ToTable("resource_calendar_revisions", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("RecurringShiftResourceCalendarRevisionId", "RecurringShiftId");
                                });

                            b1.OwnsOne("SpaceOS.Modules.Scheduling.Domain.Resources.DayRange", "Shift", b2 =>
                                {
                                    b2.Property<Guid>("RecurringShiftResourceCalendarRevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("RecurringShiftId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("EndMinuteOfDay")
                                        .HasColumnType("integer");

                                    b2.Property<int>("StartMinuteOfDay")
                                        .HasColumnType("integer");

                                    b2.HasKey("RecurringShiftResourceCalendarRevisionId", "RecurringShiftId");

                                    b2.ToTable("resource_calendar_revisions", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("RecurringShiftResourceCalendarRevisionId", "RecurringShiftId");
                                });

                            b1.Navigation("Breaks");

                            b1.Navigation("Shift")
                                .IsRequired();
                        });

                    b.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Resources.CalendarException", "Exceptions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("kind");

                            b1.Property<string>("Reason")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("calendar_revision_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("calendar_revision_id", "Date")
                                .HasDatabaseName("ix_calendar_exceptions_revision_date");

                            b1.ToTable("calendar_exceptions", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("calendar_revision_id");

                            b1.OwnsOne("SpaceOS.Modules.Scheduling.Domain.Resources.DayRange", "Span", b2 =>
                                {
                                    b2.Property<Guid>("CalendarExceptionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("EndMinuteOfDay")
                                        .HasColumnType("integer")
                                        .HasColumnName("end_minute_of_day");

                                    b2.Property<int>("StartMinuteOfDay")
                                        .HasColumnType("integer")
                                        .HasColumnName("start_minute_of_day");

                                    b2.HasKey("CalendarExceptionId");

                                    b2.ToTable("calendar_exceptions", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("CalendarExceptionId");
                                });

                            b1.Navigation("Span");
                        });

                    b.Navigation("Exceptions");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRun", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("content_hash");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("state");

                            b1.Property<Guid>("run_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("run_id", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ux_schedule_revisions_run_sequence");

                            b1.ToTable("schedule_revisions", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("run_id");

                            b1.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Schedules.OperationPlan", "Operations", b2 =>
                                {
                                    b2.Property<Guid>("revision_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("OperationId")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("operation_id");

                                    b2.Property<bool>("AutomaticallyPlanned")
                                        .HasColumnType("boolean")
                                        .HasColumnName("automatically_planned");

                                    b2.Property<decimal>("FinishMinute")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("finish_minute");

                                    b2.Property<string>("ResourceKey")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("resource_key");

                                    b2.Property<decimal>("StartMinute")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("start_minute");

                                    b2.HasKey("revision_id", "OperationId");

                                    b2.ToTable("operation_plans", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("revision_id");

                                    b2.OwnsOne("SpaceOS.Modules.Scheduling.Domain.Schedules.KernelWorkScope", "Scope", b3 =>
                                        {
                                            b3.Property<Guid>("OperationPlanrevision_id")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("OperationPlanOperationId")
                                                .HasColumnType("character varying(128)");

                                            b3.Property<Guid>("Epic")
                                                .HasColumnType("uuid")
                                                .HasColumnName("epic_ref");

                                            b3.Property<Guid>("Project")
                                                .HasColumnType("uuid")
                                                .HasColumnName("project_ref");

                                            b3.Property<Guid>("Task")
                                                .HasColumnType("uuid")
                                                .HasColumnName("task_ref");

                                            b3.HasKey("OperationPlanrevision_id", "OperationPlanOperationId");

                                            b3.HasIndex("Epic")
                                                .HasDatabaseName("ix_operation_plans_epic");

                                            b3.ToTable("operation_plans", "scheduling");

                                            b3.WithOwner()
                                                .HasForeignKey("OperationPlanrevision_id", "OperationPlanOperationId");
                                        });

                                    b2.Navigation("Scope")
                                        .IsRequired();
                                });

                            b1.Navigation("Operations");
                        });

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Standards.OperationStandard", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Standards.StandardRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("DefaultDependency")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("default_dependency");

                            b1.Property<DateTimeOffset>("ImportedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("imported_at_utc");

                            b1.Property<decimal?>("ReleaseThresholdFraction")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("release_threshold_fraction");

                            b1.Property<int>("Revision")
                                .HasColumnType("integer")
                                .HasColumnName("revision");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("state");

                            b1.Property<decimal?>("UnitMinutes")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_minutes");

                            b1.Property<decimal?>("Workforce")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("workforce");

                            b1.Property<int[]>("_quarantineReasons")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("quarantine_reasons");

                            b1.Property<Guid>("standard_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("standard_id");

                            b1.ToTable("standard_revisions", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("standard_id");
                        });

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
