// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Scheduling.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Scheduling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulingDbContext))]
    [Migration("20260728142438_InitialSchedulingSchema")]
    partial class InitialSchedulingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scheduling")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("Project")
                        .HasColumnType("uuid")
                        .HasColumnName("project_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_schedule_runs_tenant_id");

                    b.ToTable("schedule_runs", "scheduling");
                });

            modelBuilder.Entity("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRun", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Schedules.ScheduleRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("content_hash");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("state");

                            b1.Property<Guid>("run_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("run_id", "Sequence")
                                .IsUnique()
                                .HasDatabaseName("ux_schedule_revisions_run_sequence");

                            b1.ToTable("schedule_revisions", "scheduling");

                            b1.WithOwner()
                                .HasForeignKey("run_id");

                            b1.OwnsMany("SpaceOS.Modules.Scheduling.Domain.Schedules.OperationPlan", "Operations", b2 =>
                                {
                                    b2.Property<Guid>("revision_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("OperationId")
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("operation_id");

                                    b2.Property<bool>("AutomaticallyPlanned")
                                        .HasColumnType("boolean")
                                        .HasColumnName("automatically_planned");

                                    b2.Property<decimal>("FinishMinute")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("finish_minute");

                                    b2.Property<string>("ResourceKey")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)")
                                        .HasColumnName("resource_key");

                                    b2.Property<decimal>("StartMinute")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("start_minute");

                                    b2.HasKey("revision_id", "OperationId");

                                    b2.ToTable("operation_plans", "scheduling");

                                    b2.WithOwner()
                                        .HasForeignKey("revision_id");

                                    b2.OwnsOne("SpaceOS.Modules.Scheduling.Domain.Schedules.KernelWorkScope", "Scope", b3 =>
                                        {
                                            b3.Property<Guid>("OperationPlanrevision_id")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("OperationPlanOperationId")
                                                .HasColumnType("character varying(128)");

                                            b3.Property<Guid>("Epic")
                                                .HasColumnType("uuid")
                                                .HasColumnName("epic_ref");

                                            b3.Property<Guid>("Project")
                                                .HasColumnType("uuid")
                                                .HasColumnName("project_ref");

                                            b3.Property<Guid>("Task")
                                                .HasColumnType("uuid")
                                                .HasColumnName("task_ref");

                                            b3.HasKey("OperationPlanrevision_id", "OperationPlanOperationId");

                                            b3.HasIndex("Epic")
                                                .HasDatabaseName("ix_operation_plans_epic");

                                            b3.ToTable("operation_plans", "scheduling");

                                            b3.WithOwner()
                                                .HasForeignKey("OperationPlanrevision_id", "OperationPlanOperationId");
                                        });

                                    b2.Navigation("Scope")
                                        .IsRequired();
                                });

                            b1.Navigation("Operations");
                        });

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
